export const experiences = [
  {
    work_id: "wealthsimple",
    company: "Wealthsimple",
    from: "May 2024",
    to: "August 2024",
    worktype: "Co-op",
    position: "Software Engineer Intern",
    short_position: "SWE Intern",
    location: "Toronto, ON",
    images: ["/wealthsimpleImage.webp"],
    description: [
      "At Wealthsimple, I was part of the Order Generation Team. I contributed to optimizing the trading algorithm architecture by building a new data infrastructure with AWS S3 and RedShift, significantly reducing latency by about 80%, enabling faster trade order execution. As the primary technical owner of the order generation simulation platform, I built tools enabling traders to customize algorithm behavior in minutes, providing a much faster market-fluctuation reaction time",
      "I also engineered a full-stack web simultion platform with a React Native and TypeScript frontend, Ruby on Rails intergration backend, and Python GraphQL API server, integrating Datadog and Preset for monitoring. My team managed systems processing billions annually, delivering scalable, test-driven solutions for complex managed investing trading workflows.",
      "Beyond engineering, I led HackSimple Summer 2024 as a co-DRI, organizing a company-wide internal hackathon.",
    ],
    technologies: [
      "Python",
      "Ruby of Rails",
      "React Native",
      "TypeScript",
      "Kubernetes",
      "Apache Airflow",
      "GraphQL",
      "AWS",
      "Datadog",
      "PostgreSQL",
    ],
    link: "https://www.wealthsimple.com/",
    companylogo: "/wealthsimplelogo.webp",
    width: "50",
    height: "40",
  },
  {
    work_id: "rbc",
    company: "Royal Bank of Canada",
    from: "May 2023",
    to: "April 2024",
    worktype: "Co-op",
    position: "Software Engineer Intern",
    short_position: "SWE Intern",
    location: "Toronto, ON",
    images: ["/rbcImage7.webp", "/rbcImage4.webp"],
    description: [
      "I interned as a Software Engineer for the Helios ML and data platform Team at the RBC Innovation and Technology, where I worked on full-stack development, data engineering, and DevOps.",
      "I engineered a more efficient log parsing system infrastructure for GitHub Actions CI/CD pipelines using AWS S3, PostgreSQL, Apache Kafka, Apache Spark, and Python. This made data ingestion and log analysis process low latent and scalable, providing valuable data for our deployment process and generating datasets for ML model training infrastructure. I built a full-stack web platform using React alongside a Django back-end. These dashboards included mathematical calculations to offer DevOps DORA and SPACE metric insights boosting enterprise lead time by 32%.",
      "I created and deployed 10+ ETL DAG pipelines for scheduled data tasks, making data collection, storage, and analysis more streamlined by integrating with Elasticsearch through Apache Airflow orchestration. I also led the development of the Helios Assist AI autopilot extension, with fine-tuned Mistral Instruct-7B & GPT-4 LLMs on-prem AWS SageMaker, with RAG architecture, LangChain FastAPI backend and vector database embeddings, providing AI-driven coding assistance to RBC engineers for Helios deployments.",
      "Throughout these projects, I worked collaboratively in an agile development environment, ensuring the timely delivery of high-quality software solutions.",
    ],
    technologies: [
      "Python",
      "Django",
      "React.js",
      "Large Language Models",
      "PostgreSQL",
      "TypeScript",
      "Apache Airflow",
      " Apache Kafka",
      "Apache Spark",
      "Kubernetes",
      "Docker",
      "Openshift OCP4",
      "Langchain",
      "Machine Learning",
    ],
    link: "https://www.rbccm.com/en/",
    companylogo: "/rbc.webp",
    width: "200",
    height: "30",
  },
  {
    work_id: "scotiabank",
    company: "Scotiabank GBM",
    from: "May 2022",
    to: "August 2022",
    worktype: "Internship",
    position: "Trading Floor Software Developer Intern",
    short_position: "SDE Intern",
    location: "Toronto, ON",
    images: ["/scotiaImage3.webp", "/scotiaImage1.webp", "/scotiaImage2.webp"],
    description: [
      "I interned at Scotiabank as a Trading Floor Software Developer Intern in the Global Banking and Markets Technology Team. In this role, I worked on Scotiabank's trading floor, engineering full-stack web development (C#) projects and enhancing web-based systems.",
      "As part of the Global Banking & Markets team, I analyzed business processes, liaised with various groups within the bank, engineered web systems, and maintained robost infrastructure to meet trading needs. I had the chance to work with advanced web development technologies, including large datasets, bulk editing, APIs, encryption, and intelligent prediction using analytics/machine learning.",
      "I engineered 4 full-stack web projects, Email Communication Archive System, File Validator (along with its API), JSON to Excel (along with its API), and SSH-File-Transfer API.",
      "It was an excellent opportunity to learn and grow personally, gaining exposure to capital markets and the financial world. The opportunity to collaborate with the other engineers on the team was a great way to learn more about their approaches and experiences.",
      "At the GBM tech showcase, I presented my projects to the COO and executives of GBM, discussing the impact, utility, and benefits of the tools.",
    ],
    technologies: [
      ".NET Framework",
      "JavaScript",
      "C# Programming Language",
      "HTML & CSS",
      "RESTful API's",
      "SSH & HTTP",
      "jQuery",
      "React.js",
    ],
    link: "https://www.gbm.scotiabank.com/",
    companylogo: "/scotialogo.webp",
    width: "270",
    height: "50",
  },
  {
    work_id: "ieee",
    company: "IEEE TMU",
    from: "August 2022",
    to: "March 2023",
    worktype: "Volunteering",
    position: "Software Engineer Volunteer",
    short_position: "SWE Volunteer",
    location: "Toronto, ON",
    images: ["/ieeeevent1.webp", "/ieeeevent2.webp"],
    description: [
      "Volunteered with IEEE Toronto Metropolitan University as a Software Engineer. My role included engineering, designing and maintaining the IEEE TMU website and online registration systems.",
      "With the university changing its name from Ryerson University to Toronto Metropolitan University, I'm worked on creating a new robust, modern UI that boldly represents the goals of the university simultaneously being precise, clean, and capturing for the users.",
      "I further assisted the team in organizing events like IEEE Industry Night and reached out to TMU Alumni working at leading tech firms to invite them to represent their organizations and provide career advice to TMU engineering and computer science students.",
    ],
    technologies: [],
    link: "https://ieeetorontomu.ca/",
    companylogo: "/ieeelogo.webp",
    width: "200",
    height: "100",
  },
  {
    work_id: "enactus",
    company: "Enactus TMU",
    from: "October 2021",
    to: "February 2022",
    worktype: "Part Time",
    position: "Lead Full-Stack Developer (TO-Thrive Start-up)",
    short_position: "Full-Stack SDE",
    location: "Toronto, ON",
    images: [],
    description: [
      "In my first year, I got the chance to work part-time with TO-Thrive, which was a small e-commerce startup under the incubator Enactus Toronto Metropolitan University. Working as a Lead Full-Stack Developer, I collaborated on creating the TO-Thrive Website. I was responsible for the front-end development and the back-end integration of the website.",
      "As a freshman, without any experience it was a great way to learn the functioning of a small organization. TO Thrive aims to help artists leverage emerging technologies to empower them to make a living wage doing what they love. Feel free to check out this awesome startup at Enactus.",
    ],
    technologies: [],
    link: "https://www.linkedin.com/company/sife-ryerson/?originalSubdomain=ca",
    companylogo: "/enactuslogo.webp",
    width: "200",
    height: "100",
  },
];
